set(CPACK_PACKAGE_NAME "mcpelauncher-ui-qt")
set(CPACK_PACKAGE_VENDOR "Unofficial Bedrock APK Launcher contributors")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Unofficial local APK import and launch UI for mcpelauncher")
set(CPACK_PACKAGE_CONTACT "https://github.com/Abid-speedcuber/mcpelauncher-ui-qt/issues")
set(CPACK_PACKAGE_VERSION "${MANIFEST_GIT_COMMIT_HASH}")
set(CPACK_GENERATOR "TGZ;DEB")
set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_CURRENT_BINARY_DIR};mcpelauncher-ui-qt;mcpelauncher-ui-qt;/")
set(CPACK_OUTPUT_CONFIG_FILE CPackConfig.cmake)
set(CPACK_DEBIAN_PACKAGE_VERSION "${BUILD_TIMESTAMP}-${MANIFEST_GIT_COMMIT_HASH}")
if (DEB_OS_NAME MATCHES "ubuntu-xenial")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>=2.14), libssl1.0.0, libuv1, libzip4, libprotobuf9v5, qt59base, qt59declarative, qt59quickcontrols, qt59quickcontrols2, qt59svg, qt59webengine")
    set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_DEBIAN_PACKAGE_VERSION}~xenial")
elseif(DEB_OS_NAME MATCHES "ubuntu-bionic")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>=2.14), libssl1.1, libuv1, libzip4, libqt5widgets5, libqt5webenginewidgets5, libqt5quick5, libqt5svg5, libqt5quickcontrols2-5, libqt5quicktemplates2-5, libqt5concurrent5, libprotobuf10, qml-module-qtquick2, qml-module-qtquick-layouts, qml-module-qtquick-controls, qml-module-qtquick-controls2, qml-module-qtquick-window2, qml-module-qtquick-dialogs, qml-module-qt-labs-settings, qml-module-qt-labs-folderlistmodel")
elseif(DEB_OS_NAME MATCHES "ubuntu-disco")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>=2.14), libssl1.1, libuv1, libzip5, libqt5widgets5, libqt5webenginewidgets5, libqt5quick5, libqt5svg5, libqt5quickcontrols2-5, libqt5quicktemplates2-5, libqt5concurrent5, libprotobuf17, qml-module-qtquick2, qml-module-qtquick-layouts, qml-module-qtquick-controls, qml-module-qtquick-controls2, qml-module-qtquick-window2, qml-module-qtquick-dialogs, qml-module-qt-labs-settings, qml-module-qt-labs-folderlistmodel")
    set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_DEBIAN_PACKAGE_VERSION}~disco")
endif()

if(NOT CPACK_DEBIAN_PACKAGE_DEPENDS)
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "flatpak, libc6, libzip4t64 | libzip4, zlib1g, libqt6core6t64 | libqt6core6, libqt6quick6, libqt6widgets6t64 | libqt6widgets6, libqt6svg6, libqt6concurrent6t64 | libqt6concurrent6, qml6-module-qtquick, qml6-module-qtquick-controls, qml6-module-qtquick-layouts, qml6-module-qtquick-window, qml6-module-qtquick-dialogs, qml6-module-qtquick-templates")
endif()

include(CPack)
